/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * DBeanPanel.java
 *
 * Created on 1/10/2011, 12:57:26 PM
 */

package sba.lib.gui.bean;

import javax.swing.JPanel;
import sba.lib.DLibConsts;
import sba.lib.db.DDbRegistry;
import sba.lib.gui.DGuiClient;
import sba.lib.gui.DGuiConsts;
import sba.lib.gui.DGuiField;
import sba.lib.gui.DGuiFields;
import sba.lib.gui.DGuiPanel;
import sba.lib.gui.DGuiValidation;

/**
 *
 * @author Sergio Flores
 */
public abstract class DBeanPanel extends JPanel implements DGuiPanel {

    protected DGuiClient miClient;
    protected int mnPanelStatus;
    protected DGuiFields moFields;

    /** Creates new form DBeanPanel */
    public DBeanPanel() {
        initComponents();
        initComponentsBean();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new java.awt.BorderLayout());
    }// </editor-fold>//GEN-END:initComponents

    private void initComponentsBean() {
        miClient = null;
        mnPanelStatus = DLibConsts.UNDEFINED;
        moFields = new DGuiFields();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

    /*
     * Public methods
     */

    public JPanel getBeanPanel() {
        return this;
    }

    /*
     * Overriden methods
     */

    @Override
    public int getPanelStatus() {
        return mnPanelStatus;
    }

    @Override
    public void setPanelSettings(DGuiClient client) {
        miClient = client;
    }

    @Override
    public void setPanelEditable(boolean editable) {
        if (editable) {
            mnPanelStatus = DGuiConsts.FORM_STATUS_EDIT;
            moFields.setFieldsEditable(true);
        }
        else {
            mnPanelStatus = DGuiConsts.FORM_STATUS_READ;
            moFields.setFieldsEditable(false);
        }
    }

    public abstract void addAllListeners();
    public abstract void removeAllListeners();
    public abstract void reloadCatalogues();
    public abstract void setRegistry(DDbRegistry registry) throws Exception;
    public abstract DDbRegistry getRegistry() throws Exception;
    public abstract DGuiValidation validatePanel();

    @Override
    public DGuiField getFieldFirst() {
        DGuiField fieldFirst = null;

        for (DGuiField field : moFields.getFields()) {
            if (field.isFocusable()) {
                fieldFirst = field;
                break;
            }
        }

        return fieldFirst;
    }

    @Override
    public DGuiField getFieldLast() {
        DGuiField fieldLast = null;

        for (int i = moFields.getFields().size() - 1; i >= 0; i--) {
            if (moFields.getFields().get(i).isFocusable()) {
                fieldLast = moFields.getFields().get(i);
                break;
            }
        }

        return fieldLast;
    }

    @Override
    public DGuiFields getFields() {
        return moFields;
    }

    @Override
    public void setValue(int type, Object value) {
        throw new UnsupportedOperationException("Not supported yet.");
    }

    @Override
    public Object getValue(int type) {
        throw new UnsupportedOperationException("Not supported yet.");
    }
}
