/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * DGridFilterDateType.java
 *
 * Created on 4/09/2011, 11:56:10 PM
 */

package sba.lib.grid;

import javax.swing.JPanel;
import sba.lib.DLibConsts;
import sba.lib.gui.DGuiClient;

/**
 *
 * @author Sergio Flores
 */
public class DGridFilterDateType extends JPanel implements DGridFilter {

    protected DGuiClient miClient;
    protected DGridPaneView moPaneView;

    /** Creates new form DGridFilterDateType */
    public DGridFilterDateType(DGuiClient client, DGridPaneView paneView) {
        miClient = client;
        moPaneView = paneView;
        initComponents();
        initComponentsCustom();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbgGroup = new javax.swing.ButtonGroup();
        jtbDateEvent = new javax.swing.JToggleButton();
        jtbDateDocument = new javax.swing.JToggleButton();

        setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        jbgGroup.add(jtbDateEvent);
        jtbDateEvent.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sba/lib/img/swi_cal_evt_off.gif"))); // NOI18N
        jtbDateEvent.setToolTipText("Fecha evento");
        jtbDateEvent.setPreferredSize(new java.awt.Dimension(23, 23));
        jtbDateEvent.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/sba/lib/img/swi_cal_evt_on.gif"))); // NOI18N
        jtbDateEvent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtbDateEventActionPerformed(evt);
            }
        });
        add(jtbDateEvent);

        jbgGroup.add(jtbDateDocument);
        jtbDateDocument.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sba/lib/img/swi_cal_doc_off.gif"))); // NOI18N
        jtbDateDocument.setToolTipText("Fecha documento");
        jtbDateDocument.setPreferredSize(new java.awt.Dimension(23, 23));
        jtbDateDocument.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/sba/lib/img/swi_cal_doc_on.gif"))); // NOI18N
        jtbDateDocument.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtbDateDocumentActionPerformed(evt);
            }
        });
        add(jtbDateDocument);
    }// </editor-fold>//GEN-END:initComponents

    private void jtbDateEventActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtbDateEventActionPerformed
        moPaneView.putFilter(DGridConsts.FILTER_DATE_TYPE, DGridConsts.DATE_TYPE_EVT);
    }//GEN-LAST:event_jtbDateEventActionPerformed

    private void jtbDateDocumentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtbDateDocumentActionPerformed
        moPaneView.putFilter(DGridConsts.FILTER_DATE_TYPE, DGridConsts.DATE_TYPE_DOC);
    }//GEN-LAST:event_jtbDateDocumentActionPerformed

    private void initComponentsCustom() {
        jtbDateEvent.setSelected(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup jbgGroup;
    private javax.swing.JToggleButton jtbDateDocument;
    private javax.swing.JToggleButton jtbDateEvent;
    // End of variables declaration//GEN-END:variables

    /**
     * @param value Date type event, constants defined in DGridConsts (DATE_TYPE_...).
     */
    @Override
    public void initFilter(Object value) {
        switch ((Integer) value) {
            case DGridConsts.DATE_TYPE_EVT:
                jtbDateEvent.setSelected(true);
                moPaneView.getFiltersMap().put(DGridConsts.FILTER_DATE_TYPE, DGridConsts.DATE_TYPE_EVT);
                break;
            case DGridConsts.DATE_TYPE_DOC:
                jtbDateDocument.setSelected(true);
                moPaneView.getFiltersMap().put(DGridConsts.FILTER_DATE_TYPE, DGridConsts.DATE_TYPE_DOC);
                break;
            default:
                miClient.showMsgBoxError(DLibConsts.ERR_MSG_OPTION_UNKNOWN);
        }
    }
}
